export const GET_TIMELINE_POST_SUCCESS = "GET_TIMELINE_POST_SUCCESS";
export const GET_TIMELINE_POST_BEGIN = "GET_TIMELINE_POST_BEGIN";
export const GET_TIMELINE_POST_FAILURE = "GET_TIMELINE_POST_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER_BY_USERNAME_SUCCESS = "GET_USER_BY_USERNAME_SUCCESS";
export const GET_USER_BY_USERNAME_BEGIN = "GET_USER_BY_USERNAME_BEGIN";
export const GET_USER_BY_USERNAME_FAILURE = "GET_USER_BY_USERNAME_FAILURE";
export const GET_USER__POST_SUCCESS = "GET_USER__POST_SUCCESS";
export const GET_USER__POST_BEGIN = "GET_USER__POST_BEGIN";
export const GET_USER__POST_FAILURE = "GET_USER__POST_FAILURE";

export const GET_LOGIN_USER_SUCCESS = "GET_LOGIN_USER_SUCCESS";
export const GET_LOGIN_USER_BEGIN = "GET_LOGIN_USER_BEGIN";
export const GET_LOGIN_USER_FAILURE = "GET_LOGIN_USER_FAILURE";
export const GET_REGISTER_USER_SUCCESS = "GET_REGISTER_USER_SUCCESS";
export const GET_REGISTER_USER_BEGIN = "GET_REGISTER_USER_BEGIN";
export const GET_REGISTER_USER_FAILURE = "GET_REGISTER_USER_FAILURE";

export const GET_LIKE_SUCCESS = "GET_LIKE_SUCCESS";
export const GET_LIKE_BEGIN = "GET_LIKE_BEGIN";
export const GET_LIKE_FAILURE = "GET_LIKE_FAILURE";

export const GET_CREATE_POST_SUCCESS = "GET_CREATE_POST_SUCCESS";
export const GET_CREATE_POST_BEGIN = "GET_CREATE_POST_BEGIN";
export const GET_CREATE_POST_FAILURE = "GET_CREATE_POST_FAILURE";

export const GET_FOLLOW_FIREND_SUCCESS = "GET_FOLLOW_FIREND_SUCCESS";
export const GET_FOLLOW_FIREND_BEGIN = "GET_FOLLOW_FIREND_BEGIN";
export const GET_FOLLOW_FIREND_FAILURE = "GET_FOLLOW_FIREND_FAILURE";
export const GET_UNFOLLOW_FIREND_SUCCESS = "GET_UNFOLLOW_FIREND_SUCCESS";
export const GET_UNFOLLOW_FIREND_BEGIN = "GET_FUNOLLOW_FIREND_BEGIN";
export const GET_UNFOLLOW_FIREND_FAILURE = "GET_UNFOLLOW_FIREND_FAILURE";

export const UPDATE_POST_BEGIN = "UPDATE_POST_BEGIN";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";
